apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: 'gatekeeper'
  namespace: argocd
spec:
  project: default
  sources:
  - repoURL: 'https://open-policy-agent.github.io/gatekeeper/charts'
    targetRevision: 3.12.0
    chart: gatekeeper
  - repoURL: 'https://github.com/silveraignacio/argocd-poc.git'
    path: opa-exporter
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: gatekeeper-system
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
